apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-lego.fullname" . }}-default-backend
  labels:
    snappyflow/compname: abcd
    snappyflow/appname: projectags-stage
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ template "nginx-lego.fullname" . }}-default-backend
